name: 'Release'

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: install frontend dependencies
        run: npm install
        working-directory: ./gui

      - name: build tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'Zapret2 ${{ github.ref_name }}'
          releaseBody: |
            ** Что нового в версии 2.1.0:**
            - **Добавлен GameFilter:** Глобальный обход DPI на всех портах для работы онлайн-игр (Roblox, Rocket League и т.д.). Активируется одним тумблером в GUI.
            - **Ускорен Авто-подбор:** Таймауты снижены в несколько раз. Скрипт тестирования пролетает намного быстрее.
            - **Новые цели для тестов:** Добавлена проверка сайтов Twitch и Roblox в автоматическом режиме.
            - **Фиксы UI:** Починено отображение логов терминала при тесте кастомных пресетов; добавлена обводка для тумблера.
          releaseDraft: false
          prerelease: false
          projectPath: './gui'
